version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    environment:
      REPO: michaelvl/conftest-kubernetes
      CONFTEST_VERSION: "v0.16.0"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variables
          command: |
            echo "REPO=$REPO" >> $BASH_ENV
            GITCOMMIT=${CIRCLE_SHA1::7}
            NOW=$(date +%Y%m%d-%H%M)
            FULLNAME="$REPO:$NOW-$GITCOMMIT-$CONFTEST_VERSION"
            echo "FULLNAME=$FULLNAME" >> $BASH_ENV
            echo "Branch $CIRCLE_BRANCH"
            echo "Using full name $FULLNAME"
            echo "Using version $CONFTEST_VERSION"
      - run:
          name: Build container image
          command: |
            docker build --build-arg CONFTEST_VERSION=$CONFTEST_VERSION -t $FULLNAME .
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag $FULLNAME $REPO:latest
            fi
      - run:
          name: Push container image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $REPO
